#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

process = os.popen("ps -aux | grep ethOS-update-manager").readlines()
is_working = ["src/updater.py" in p for p in process]

if True not in is_working :  
	os.system("nohup python3 /home/ethos/ethOS-update-manager/src/updater.py >> /home/ethos/ethOS-update-manager/logs/updater.log 2>&1 &")

