#!/usr/bin/env python3
#--*-- coding: utf-8 --*--


"""
install program for ethOS-update-manager
"""

# import 
import os, time


# prepare sys
os.system("cd /home/ethos/")
os.system("chmod +x /home/ethos/ethOS-update-manager/launch.py")
os.system("chmod +x /home/ethos/ethOS-update-manager/src/main.py")


# title in .bashrc
os.system("""echo ' ' >> /home/ethos/.bashrc """)
os.system("""echo ' ' >> /home/ethos/.bashrc """)
os.system("""echo '################################' >> /home/ethos/.bashrc """)
os.system("""echo '#	ethOS-update-manager' >> /home/ethos/.bashrc """)
os.system("""echo '################################' >> /home/ethos/.bashrc """)


# one blanck line
os.system("""echo ' ' >> /home/ethos/.bashrc """)


# create alias (shortcup for CLI) 'LAUNCH' to launch program manualy : 
os.system("""echo '# create alias (shortcup for CLI) 'LAUNCH' to launch program manualy :' >> /home/ethos/.bashrc """)
os.system("""echo "alias LAUNCH='python3 /home/ethos/ethOS-update-manager/launch.py'" >> /home/ethos/.bashrc """)


# one blanck line
os.system("""echo ' ' >> /home/ethos/.bashrc """)


# for automatic program launch (background) at each ethos stratup :
os.system("""echo '# for automatic program launch (background) at each ethos stratup:' >> /home/ethos/.bashrc """)
os.system("""echo 'python3 /home/ethos/ethOS-update-manager/launch.py' >> /home/ethos/.bashrc """)


# info reboot
print("for full install, system will reboot in : ")
for i in range(4, 0, -1) : 
	print(str(i-1))
	time.sleep(1)


#auto reboot 
ans = os.system("r")
if ans : 
	ans = os.system("reboot")
	if ans : 
		ans = os.system("sudo reboot")
		if ans : 
			print(	"\n\n"
					"#######################################\n"
					"auto reboot fail, please reboot manualy\n"
					"#######################################\n")