#!/usr/bin/env python3
#--*-- coding: utf-8 --*--


"""
install script for ethOS-update-manager
chmod exec for launch.py and main.py
create aliases and cmd for autoclaunch in .bashrc with fancy text
try to reboot 
"""


# import 

from src._install import * 


# main

def main() : 
	prepare_system()
	write_title()
	write_alias()
	write_autolaunch()
	reboot()


if __name__ == '__main__':
	main()

