#!/usr/bin/env python3
#--*-- coding: utf-8 --*--

import os

# nohup to free comand from terminal
# > log to keep a log of exe 
# 2>&1 to log both stderr and stdout 
# & to execute program in background



process = os.popen("ps -aux | grep ethOS-update-manager").readlines()
is_working = ["src/main.py" in p for p in process]

if True not in is_working :  
	os.system("nohup python3 /home/ethos/ethOS-update-manager/src/main.py >> /home/ethos/ethOS-update-manager/logs/log 2>&1 &")

