#!/usr/bin/env python3
#--*-- coding: utf-8 --*--



import os, sys


def main(): 
	res = os.popen("ps -aux | grep ethOS-update-manager").readlines()
	res = [i for i in res if "ethOS-update-manager/" in i]
	res = "".join(res)
	print(res)



if __name__ == '__main__':
	main()